#!/bin/bash

drivelist=$(lsblk -lp | grep "t /mnt"* | awk '{ print $1 "("$4")""-"$7}' | dmenu -i -p "Select disk to unmount" -fn "Roboto condensed") #Lists all mounted drives in /mnt

if [[ -z $drivelist ]]; then
		notify-send "There is no drive to unmount!" && exit 1
fi

drive=${drivelist#*-}

sudo -A umount $drive && pgrep -x dunst && notify-send "$drivelist unmounted" && exit 0
